[project]
name = "arrow-demo"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "youssef", email = "me@gmail.com" }
]
requires-python = ">=3.14"
dependencies = [
    "pandas>=3.0.6",
    "psutil>=7.2.2",
    "pyarrow>=25.0.1",
    "pyspark>=4.2.0",
    "rich>=15.0.0",
]

[project.scripts]
arrow-demo = "arrow_demo:main"

[build-system]
requires = ["uv_build>=0.12.13,<0.13.0"]
build-backend = "uv_build"
